#!/bin/bash

# Define the key file names
private_key_file="school"
public_key_file="${private_key_file}.pub"

# Define the number of bits for the key
key_bits=4096

# Define the passphrase
passphrase="betty"

# Check if the private key file already exists
if [ -f "$private_key_file" ]; then
  echo "Private key file '$private_key_file' already exists."
  exit 1
fi

# Generate the RSA key pair with the specified number of bits and passphrase
ssh-keygen -t rsa -b "$key_bits" -f "$private_key_file" -N "$passphrase"

# Check if the key generation was successful
if [ $? -eq 0 ]; then
  echo "RSA key pair created successfully."
else
  echo "Failed to create the RSA key pair."
fi
